services:
  accounts:
    image: "sadoyol/accounts:0.0.1-SNAPSHOT"
    container_name: accounts-microservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sadoyol
  loans:
    image: "sadoyol/loans:0.0.1-SNAPSHOT"
    container_name: loans-microservice
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sadoyol
  cards:
    image: "sadoyol/cards:0.0.1-SNAPSHOT"
    container_name: cards-microservice
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sadoyol
networks:
  sadoyol:
    driver: "bridge"