# application-qa.yml
spring:
  config:
    activate:
      on-profile: qa
build:
  version: 0.0.2
accounts:
  message: "Loans Microservice related to quality assurance"
  contactDetails:
    name: Sait Yolal - QA
    email: msaityolal@gmail.com
    github: https://github.com/msaityolal