build:
  version: 0.0.2
cards:
  message: "Cards Microservice related to quality assurance"
  contactDetails:
    name: Sait Yolal - QA
    email: msaityolal@gmail.com
    github: https://github.com/msaityolal